### ISSUE TITLE
problems with midi library

### ISSUE THREAD

**Issue by primvla** [arduino-libraries/Servo#108]
Hello, I'm not much of a programmer and I'm having problems with a project where I plan to control some things by reading midi (music to mechatronics). If I include <Servo.h> in my project, midi stops working (servo test procedures do work as expected). There's no compiler error, just midi messages like NoteON event don't come thru (just by including servo header and nothing more).

I'm bypassing the midi library (https://github.com/FortySevenEffects/arduino_midi_library) with reading and analyzing serial bytes, but I find that rather tedious. Is there any chance someone experienced could compare the two libraries and identify the culprit?

**Comment by per1234** [comment]
Hi @primvla. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
