### ISSUE TITLE
No PWM output on PWM pins with Nano 33 Sense

### ISSUE THREAD

**Issue by andamado997** [arduino-libraries/Servo#36]
I was trying to run some tests with servos on my Nano 33 Sense and I noticed that every time I loaded a test sketch (sweep sketch from the examples folder), My servo was unresponsive. I connected the Nano's PWM pin to a scope (pinout 21 or D3 in this case, but I had also tried the others as well) and I was getting nothing on the scope. I had hooked up and loaded the same sketch to an Arduino MEGA 2560 and I could see the pulse sweep on the scope. Any idea as to why my nano 33 sense would not be working correctly like the MEGA?

**Comment by facchinm** [comment]
Fixed by #32
