### ISSUE TITLE
warning for mbed_nano architecture

### ISSUE THREAD

**Issue by montoyamoraga** [arduino-libraries/Servo#74]
i have been using this library with an Arduino Nano 33 BLE Sense,
and Arduino released a new core for it, where the architecture is named mbed_nano
so now i have a warning that says
"
WARNING: library Servo claims to run on avr, megaavr, sam, samd, nrf52, stm32f4, mbed architecture(s) and may be incompatible with your current board which runs on mbed_nano architecture(s).
"

**Comment by withinboredom** [comment]
@montoyamoraga just curious, how did you get this to compile? I receive the following error:

> error: 'DigitalOut' in namespace 'mbed' does not name a type

**Comment by withinboredom** [comment]
I guess it helps to install the library.

**Comment by montoyamoraga** [comment]
this was already resolved

**Comment by bilal697** [comment]
> this was already resolved

How to solve for mbed_nano-architecture.

**Comment by per1234** [comment]
@bilal697 as mentioned above it was already resolved quite some time ago. Just make sure you are using the latest 1.1.8 version of the Servo library. You can check the version and update the library in the Arduino IDE's Library Manager (**Sketch > Include Libraries > Manage Libraries...**).

If you have any questions, you're welcome to post on the Arduino Forum:
https://forum.arduino.cc/
