### ISSUE TITLE
Raspberry Pico Compatibility; servo read response

### ISSUE THREAD

**Issue by PJ789** [arduino-libraries/Servo#90]
When I use servo.read on a Pico, the result returned seems to be two or three degrees wrong versus the last request to servo.write.

In the Arduino documentation it states; "Read the current angle of the servo (**the value passed to the last call to write()**)."

**Comment by per1234** [comment]
Hi @PJ789. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino-libraries/Servo/issues/65 (the library code is the same for all the Arduino Mbed OS Boards targets).

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
